### ISSUE TITLE
GOT RATTED DONT USE

### ISSUE THREAD

**Issue by Invy55** [Frennzye/Phobos-1.3.3-Improved-Compatibility#1]
This rat very well hidden using last `windows 98 antivirus bypass 2020 ncp bypass no rat no survey nodus free download nodus.com download nodus free chat client free download hack minecfrasft ffree 2013 mineplexe byuasss` that makes ur pc run anydesk and grant access to a guy called Frennzy that gift u lot of pedos but I already had so not needed, if u need just run and it should create a folder called n0tP3d0 inside a guy will put lot of photos really good ones.

### this 100000% not joke trust me

**Comment by Frennzye** [comment]
damn you exposed me

**Comment by Invy55** [comment]
> damn you exposed me

ues of curse

**Comment by Frennzye** [comment]
i thought the rat was well hidden in the windows 98 antivirus bypass 2020 ncp bypass no rat no survey nodus free download nodus.com download nodus free chat client

**Comment by Invy55** [comment]
### Imma leave this explaining there closing the issue
